### ISSUE TITLE
Trying to create a Baritone with Head

### ISSUE THREAD

**Issue by sanjeev002** [bguan/gugulele#1]
Hi,

Thanks for these script they work really well for soprano models.

I am trying to create a Baritone with head for normal closed geared tuners.

I find that when I generate the head it seems to be chopped off. The chop off section seems to go through the tuners furthest from the Nut.

Is there anything I am doing wrong?

Is there any way to reduce the size of the body on a baritone?

Thanks

**Comment by bguan** [comment]
HI Sanjeev,

Thanks for trying it out, and I am impressed you can even get it to work in the first place :-)

I am sure you are not doing anything wrong, it is likely to be bug in my code, as a headed baritone is not one of my usual test model.

I will look into it.

**Comment by bguan** [comment]
Fixed with /bguan/gugulele/commit/0a244856c3023fd6428cc29b5f1301fe5f35b7bd
